### ISSUE TITLE
Python not running Tweego-File-Splitter.py 

### ISSUE THREAD

**Issue by Kobic** [Zachac/Tweego-File-Splitter#1]
Every time I run this I get an error 

> Traceback (most recent call last):
  File "Test.py", line 1, in <module>
    import tweego_file_splitter
  File "J:\ArbitaryFilePath\Test\tweego_file_splitter.py", line 31
    print(":: ", title, file=f)
                            ^
SyntaxError: invalid syntax

I've also tried the command line but I get the same error. Is there a specific version of python I need installed? I have python 2.7.15 installed.

**Comment by Zachac** [comment]
Correct, this script was written for Python 3. Python 2 has different syntax for the print function, which is why your getting that error.

**Comment by Zachac** [comment]
I have updated the README to add this information, let me know if you have any more issues.
